### ISSUE TITLE
Crash when taking a screenshot

### ISSUE THREAD

**Issue by Felix14-v2** [ShadowMC69/VulkanMod#17]
### Description
One of some minor unresolved bugs from the old testing builds by thr3343, still exists in 0.4.2. When you press F2 (or any other bound key) to take a screenshot, the game crashes.

### To reproduce
- Install Minecraft 1.20.4
- Install Fabric (any supported version)
- Install latest [modded] VulkanMod build
- Launch the game and open a world
- Send a screenshot keybind
- Get a crash

### Logs
[latest.log](https://github.com/user-attachments/files/15779321/latest.log)

<details>
 <summary>Error info (after taking a screenshot)</summary>

```
--------- beginning of system

[00:32:59] [Render thread/ERROR] (Minecraft) Unreported exception thrown!
java.lang.RuntimeException: Failed to create buffer:-8
	at net.vulkanmod.vulkan.memory.MemoryManager.createBuffer(MemoryManager.java:111) ~[VulkanMod_1.20.4-modified_v6.2-lite.beta-0.4.2.jar:?]
	at net.vulkanmod.vulkan.texture.ImageUtil.downloadTexture(ImageUtil.java:47) ~[VulkanMod_1.20.4-modified_v6.2-lite.beta-0.4.2.jar:?]
	at net.minecraft.client.texture.NativeImage.loadFromTextureImage(NativeImage.java:779) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.ScreenshotRecorder.takeScreenshot(ScreenshotRecorder.java:530) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.ScreenshotRecorder.saveScreenshotInner(ScreenshotRecorder.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.ScreenshotRecorder.saveScreenshot(ScreenshotRecorder.java:36) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.ScreenshotRecorder.saveScreenshot(ScreenshotRecorder.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.client.Keyboard.onKey(Keyboard.java:377) ~[client-intermediary.jar:?]
	at net.minecraft.client.Keyboard.method_22678(Keyboard.java:492) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.client.Keyboard.redirect$cco000$viafabricplus$storeEvent(Keyboard.java:3136) ~[client-intermediary.jar:?]
	at net.minecraft.client.Keyboard.method_22676(Keyboard.java:492) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44) ~[lwjgl-glfw-classes.jar:?]
	at org.lwjgl.system.JNI.callJV(Native Method) ~[lwjgl-glfw-classes.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:1081) ~[lwjgl-glfw-classes.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:1618) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window.java:614) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1349) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.9-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.9.jar:?]

```
</details>

<details>
 <summary>A detailed walkthrough</summary>

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.vulkanmod.vulkan.memory.MemoryManager.createBuffer(MemoryManager.java:111)
	at net.vulkanmod.vulkan.texture.ImageUtil.downloadTexture(ImageUtil.java:47)
	at MC//net.minecraft.client.texture.NativeImage.loadFromTextureImage(NativeImage.java:779)
	at MC//net.minecraft.client.util.ScreenshotRecorder.takeScreenshot(ScreenshotRecorder.java:530)
	at MC//net.minecraft.client.util.ScreenshotRecorder.saveScreenshotInner(ScreenshotRecorder.java:41)
	at MC//net.minecraft.client.util.ScreenshotRecorder.saveScreenshot(ScreenshotRecorder.java:36)
	at MC//net.minecraft.client.util.ScreenshotRecorder.saveScreenshot(ScreenshotRecorder.java:27)
	at MC//net.minecraft.client.Keyboard.onKey(Keyboard.java:377)
	at MC//net.minecraft.client.Keyboard.method_22678(Keyboard.java:492)
	at MC//net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:102)
	at MC//net.minecraft.client.Keyboard.redirect$cco000$viafabricplus$storeEvent(Keyboard.java:3136)
	at MC//net.minecraft.client.Keyboard.method_22676(Keyboard.java:492)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.callJV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:1081)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:1618)

-- Uptime --
Details:
	JVM uptime: 171.395s
	Wall uptime: 124.471s
	High-res time: 116.422s
	Client ticks: 1404 ticks / 70.200s
Stacktrace:
	at MC//net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2564)
	at MC//net.minecraft.client.MinecraftClient.printCrashReport(MinecraftClient.java:995)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```
</details>

### System info
| Mod version | Latest (0.4.2-V6.2) |
| :--- | :--- |
| Android | 11 |
| GPU | Mali G52 MC2 |
| Supported Vulkan API | 1.1.131 [(Device report)](https://vulkan.gpuinfo.org/displayreport.php?id=14065) |
| Launcher | [PojavLauncher](https://github.com/PojavLauncherTeam/PojavLauncher) (build from 2024.05.31) |

### Additional
I personally just use the system screenshots, but some users want to separate their Minecraft screenshots from others, and fixing this would help with that. Also hiding controls layout from screenshots is only available on iOS version of PojavLauncher, so Android users could benefit even more.

**Comment by ShadowMC69** [comment]
It's a issue of android for now
